language: generic 

sudo: required

services:
  - docker

before_install:
  - docker build -t richfw12/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true richfw12/docker-react npm run test
